#!/bin/bash
# Check pcd5002.py against the one dump taken from real hardware. Everything
# else it is tested on is synthetic, generated by the same arithmetic the
# decoder uses, so this is the only case that proves the identifier bit packing
# against a configuration a real network wrote.

set -u
out=$(./pcd5002.py testdata/pcd5002_philips53d.bin) || exit 1
fail=0

check() {
    if grep -qF "$1" <<<"$out"; then
        echo "  ok    $1"
    else
        echo "  FAIL  expected: $1"; fail=1
    fi
}

echo "== PCD5002 decoder against real hardware dump =="
check "protocol        POCSAG"
check "bit rate        1200 bits/s"
check "data inversion  disabled"
check "cycle length    5 batches"
check "batch number    0"
check "RIC 1578624  frame 0  enabled"
check "RIC 683607  frame 7  enabled"
check "RIC 683615  frame 7  enabled"
check "RIC 1000000  frame 0  disabled"
check "unprogrammed"

# A real dump must not trip the consistency checks, or those checks are too eager
if grep -q "THIS DUMP LOOKS WRONG" <<<"$out"; then
    echo "  FAIL  a valid dump tripped the sanity checks"; fail=1
else
    echo "  ok    no false sanity warnings"
fi

# The frame bits are stored separately from the address bits, so agreement
# between them is independent evidence the packing is right.
python3 - <<'PY' || fail=1
d = open('testdata/pcd5002_philips53d.bin','rb').read()
get = lambda a: d[((a >> 3) * 6) + (a & 7)]
bad = 0
for n in range(6):
    b1, b2, b3 = get(0x10+n), get(0x18+n), get(0x20+n)
    if (b1, b2, b3) in ((0xFF,)*3, (0x00,)*3):
        continue
    ric = (((b1 << 10) | (b2 << 2) | ((b3 >> 6) & 3)) << 3) | ((b3 >> 3) & 7)
    if ric % 8 != ((b3 >> 3) & 7):
        print(f"  FAIL  identifier {n+1}: frame bits disagree with RIC mod 8"); bad = 1
print("  ok    frame bits agree with RIC mod 8 on every programmed slot")
raise SystemExit(bad)
PY

[ "$fail" -eq 0 ] && echo "all passed" || echo "FAILED"
exit "$fail"
